/**
 * Engine — Narrative Module
 *
 * Generates narrative interpretations for tarot readings.
 * Supports multiple narrative styles and integrates with meaning weights.
 */
import type { TarotParameters, PlacedCard, MeaningWeights } from '../types';

export type NarrativeStyle = TarotParameters['narrativeStyle'];

export interface NarrativeConfig {
  style: NarrativeStyle;
  weights: MeaningWeights;
  includePositionContext: boolean;
  maxLength?: number;
}

export interface GeneratedNarrative {
  title: string;
  sections: NarrativeSection[];
  summary: string;
  timestamp: string;
}

export interface NarrativeSection {
  heading: string;
  body: string;
  cardRef?: string;
}

/** Style configuration presets */
const STYLE_CONFIG: Record<NarrativeStyle, { tone: string; prefix: string; suffix: string }> = {
  formal: {
    tone: 'academic',
    prefix: '## Reading Analysis\n\n',
    suffix: '\n\n*— Generated by MTPS Narrative Engine (formal mode)*',
  },
  poetic: {
    tone: 'lyrical',
    prefix: '## The Tapestry Unfolds\n\n',
    suffix: '\n\n*— Woven by the MTPS Narrative Engine*',
  },
  analytical: {
    tone: 'data-driven',
    prefix: '## Analytical Breakdown\n\n',
    suffix: '\n\n*— MTPS Narrative Engine (analytical mode)*',
  },
  mystical: {
    tone: 'esoteric',
    prefix: '## Whispers of the Arcana\n\n',
    suffix: '\n\n*— Channelled through the MTPS Narrative Engine*',
  },
};

/**
 * Get the dominant meaning dimension from weights
 */
function getDominantDimension(weights: MeaningWeights): string {
  const entries = Object.entries(weights) as [string, number][];
  entries.sort((a, b) => b[1] - a[1]);
  return entries[0][0];
}

/**
 * Generate a card interpretation paragraph
 */
function interpretCard(card: PlacedCard, style: NarrativeStyle, dominant: string): string {
  const { card: c, position } = card;
  const meaning = c.isReversed ? c.meaningReversed : c.meaningUp;
  const reversal = c.isReversed ? ' (Reversed)' : '';

  const lines: string[] = [];
  lines.push(`### ${position.label}: ${c.name}${reversal}`);
  lines.push('');

  if (style === 'formal') {
    lines.push(`**Position ${position.index + 1}** — ${position.description}`);
    lines.push(`The ${c.archetype} archetype manifests in the ${dominant} dimension.`);
    lines.push(meaning);
  } else if (style === 'poetic') {
    lines.push(`*In the space of ${position.description.toLowerCase()}...*`);
    lines.push(`${c.name} emerges as ${c.archetype}, speaking through the language of ${dominant}.`);
    lines.push(meaning);
  } else if (style === 'analytical') {
    lines.push(`**[${position.label}]** Archetype: ${c.archetype} | Keywords: ${c.keywords.join(', ')}`);
    lines.push(`Primary dimension: ${dominant} | ${meaning}`);
  } else {
    lines.push(`The veil parts at the ${position.label} position...`);
    lines.push(`${c.archetype} reveals: ${meaning}`);
    lines.push(`*Keywords: ${c.keywords.join(', ')}*`);
  }

  return lines.join('\n');
}

/**
 * Generate a complete narrative for a spread
 */
export function generateNarrative(
  spread: PlacedCard[],
  config: NarrativeConfig,
): GeneratedNarrative {
  const styleConf = STYLE_CONFIG[config.style];
  const dominant = getDominantDimension(config.weights);

  const sections: NarrativeSection[] = spread.map(card => ({
    heading: `${card.position.label}: ${card.card.name}`,
    body: interpretCard(card, config.style, dominant),
    cardRef: card.card.id,
  }));

  const fullText = [
    styleConf.prefix,
    ...sections.map(s => s.body),
    styleConf.suffix,
  ].join('\n\n');

  return {
    title: styleConf.prefix.replace(/^## /, '').replace(/\n/g, '').trim(),
    sections,
    summary: fullText,
    timestamp: new Date().toISOString(),
  };
}

/**
 * Generate a one-line synthesis from a spread
 */
export function generateSynthesis(spread: PlacedCard[], weights: MeaningWeights): string {
  const dominant = getDominantDimension(weights);
  const names = spread.map(p => p.card.name).join(' → ');
  return `[${dominant.toUpperCase()}] Reading path: ${names}`;
}
